#ifndef STOCHASTIC_ANALYTIC_CONTINUATION_MEASURE_H
#define STOCHASTIC_ANALYTIC_CONTINUATION_MEASURE_H
#pragma once

/*
 *  This head file includes Measure class to obtain spectrum functions of statistical significance
 *  from weight configurations generated by SAC.
 */

class Measure {

public:


private:


};

#endif //STOCHASTIC_ANALYTIC_CONTINUATION_MEASURE_H
